ListItem.create(title: 'Venusaur', details: 'Seed Pokémon')
ListItem.create(title: 'Charizard', details: 'Flame Pokémon')
ListItem.create(title: 'Blastoise', details: 'Shellfish Pokémon')
ListItem.create(title: 'Pidgey', details: 'Tiny Bird Pokémon')
ListItem.create(title: 'Pikachu', details: 'Mouse Pokémon')
ListItem.create(title: 'Zubat', details: 'Bat Pokémon')
ListItem.create(title: 'Alakazam', details: 'Psi Pokémon')
ListItem.create(title: 'Machamp', details: 'Superpower Pokémon')
ListItem.create(title: 'Hitmonchan', details: 'Punching Pokémon')
ListItem.create(title: 'Gyarados', details: 'Atrocious Pokémon')
ListItem.create(title: 'Ditto', details: 'Transform Pokémon')
ListItem.create(title: 'Snorlax', details: 'Sleeping Pokémon')
ListItem.create(title: 'Articuno', details: 'Freeze Pokémon')
ListItem.create(title: 'Dragonite', details: 'Dragon Pokémon')
ListItem.create(title: 'Mewtwo', details: 'Genetic Pokémon')
